apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  title: "KeyVault - ${{ values.key_vault_name }}"
  description: ${{ values.description | dump }}
  annotations:
    dev.azure.com/project: "${{ values.ado_project }}"
    dev.azure.com/project-repo: "${{ values.ado_project }}/${{ values.repo_name }}"
    dev.azure.com/repo: "${{ values.repo_name }}"
    dev.azure.com/pipeline-name: "pipeline-keyvault-${{ values.repo_name }}"
    dev.azure.com/pipeline-file: "pipeline-keyvault.yml"
    azure.com/resource-type: "key-vault"
    azure.com/rg-name: "${{ values.resource_group_name }}"
    azure.com/location: "${{ values.location }}"
    azure.com/keyvault-sku: "${{ values.keyvault_sku }}"
    azure.com/keyvault-purge-protection: "${{ values.keyvault_purge_protection }}"
  tags:
    - azure
    - key-vault
    - security
    - terraform
spec:
  type: azure-key-vault
  lifecycle: experimental
  owner: ${{ values.owner }}
  dependsOn:
    - "component:default/${{ values.resource_group_name }}"
    {% if values.link_storage and values.existing_storage %}
    - "${{ values.existing_storage }}"
    {% endif %}
