apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  title: "RG - ${{ values.resource_group_name }}"
  description: ${{ values.description | dump }}
  annotations:
    dev.azure.com/project: "${{ values.ado_project }}"
    dev.azure.com/project-repo: "${{ values.ado_project }}/${{ values.repo_name }}"
    dev.azure.com/repo: "${{ values.repo_name }}"
    dev.azure.com/pipeline-name: "pipeline-resource-group-${{ values.repo_name }}"
    dev.azure.com/pipeline-file: "pipeline-resource-group.yml"
    azure.com/resource-type: "resource-group"
    azure.com/rg-name: "${{ values.resource_group_name }}"
    azure.com/location: "${{ values.location }}"
    azure.com/tag-owner: "${{ values.tag_owner }}"
    azure.com/tag-project: "${{ values.tag_project }}"
    azure.com/tag-criticality: "${{ values.tag_criticality }}"
  tags:
    - azure
    - resource-group
    - terraform
spec:
  type: azure-resource-group
  lifecycle: experimental
  owner: ${{ values.owner }}
