trigger: none

# ============================================================
# PIPELINE – RESOURCE GROUP
# Template mince : appelle le template centralisé terraform-ci-cd.yml
# ============================================================

parameters:

  - name: action
    displayName: "⚡ Action"
    type: string
    default: apply
    values: [plan, apply, destroy]

  - name: resource_group_name
    displayName: "🏷️ Nom du Resource Group"
    type: string
    default: "${{ values.resource_group_name }}"

  - name: location
    displayName: "🌍 Région"
    type: string
    default: "West Europe"
    values:
      - "West Europe"
      - "North Europe"
      - "France Central"
      - "France South"
      - "East US"
      - "East US 2"
      - "Southeast Asia"

  - name: environment
    displayName: "🌱 Environnement"
    type: string
    default: "dev"
    values: [dev, test, staging, prod, sandbox, poc]

  - name: tag_owner
    displayName: "🏷️ Tag Owner"
    type: string
    default: "MIC-SECOPS"
    values: [MIC-SECOPS, MIC-IDP, NTT-DATA, Platform-Team, DevOps-Team]

  - name: tag_project
    displayName: "🏷️ Tag Project"
    type: string
    default: "IDP-PFE"
    values: [IDP-PFE, Mail-API, PKI, DNS, SIEM, Platform]

  - name: tag_cost_center
    displayName: "🏷️ Tag Cost Center"
    type: string
    default: "MIC-001"
    values: [MIC-001, MIC-002, SECOPS-100, INFRA-200]

  - name: tag_managed_by
    displayName: "🏷️ Tag Managed By"
    type: string
    default: "Terraform"
    values: [Terraform, OpenTofu, Bicep, Manual]

  - name: tag_criticality
    displayName: "🏷️ Tag Criticality"
    type: string
    default: "Medium"
    values: [Low, Medium, High, Critical]

  - name: tag_data_classification
    displayName: "🏷️ Tag Data Classification"
    type: string
    default: "Internal"
    values: [Public, Internal, Confidential, Restricted]

resources:
  repositories:
    - repository: IDP-MIC
      type: git
      name: IDP-MIC
      ref: refs/heads/main

stages:
- template: templates/terraform-ci-cd.yml@IDP-MIC
  parameters:
    action: ${{ parameters.action }}
    service_connection: 'MIC-IDP'
    tf_working_dir: 'pipelines/resource-group'
    tfstate_key_prefix: 'rg'
    resource_group_name: ${{ parameters.resource_group_name }}
    resource_name: ${{ parameters.resource_group_name }}
    bs_resource_name_var: 'BS_RESOURCE_GROUP_NAME'
    check_rg_exists: false
    tf_extra_vars: >
      -var="location=${{ parameters.location }}"
      -var="environment=${{ parameters.environment }}"
      -var="owner=${{ parameters.tag_owner }}"
      -var="tag_project=${{ parameters.tag_project }}"
      -var="tag_cost_center=${{ parameters.tag_cost_center }}"
      -var="tag_managed_by=${{ parameters.tag_managed_by }}"
      -var="tag_criticality=${{ parameters.tag_criticality }}"
      -var="tag_data_classification=${{ parameters.tag_data_classification }}"
