apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  title: "💻 VM – dans ${{ values.resource_group_name }}"
  description: ${{ values.description | dump }}
  annotations:
    dev.azure.com/project: "${{ values.ado_project }}"
    dev.azure.com/project-repo: "${{ values.ado_project }}/${{ values.repo_name }}"
    azure.com/resource-type: "virtual-machine"
    azure.com/rg-name: "${{ values.resource_group_name }}"
    azure.com/location: "${{ values.location }}"
    azure.com/vm-size: "${{ values.vm_size }}"
    azure.com/vm-os-type: "${{ values.vm_os_type }}"
    azure.com/vm-os-image: "${{ values.vm_os_image }}"
    azure.com/vm-count: "${{ values.vm_count }}"
  tags:
    - azure
    - virtual-machine
    - compute
    - terraform
spec:
  type: azure-virtual-machine
  lifecycle: experimental
  owner: ${{ values.owner }}

